FROM python:3.8.16-alpine
WORKDIR /DjangoGram
COPY docker-entrypoint.prod.sh docker-entrypoint.prod.sh
COPY requirements.txt requirements.txt
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
COPY . .
RUN  python -m pip install --upgrade pip &&\
    apk add -u gcc musl-dev &&\
    pip install -r requirements.txt &&\
    apk del gcc musl-dev &&\
    chmod +x docker-entrypoint.prod.sh
